version: "3"

services:
  app: ##name of your container
    build: ./ ## directory with the docker-compose file
    volumes: ## dir of host fisrt then WORKDIR
      - ./:/var/lib/app
    ports:
      - 8000:8080
