version: "3"

services:
  app: ##name of your container
    build: ./ ## directory with the docker-compose file
    container_name: api_container_app
    volumes: ## dir of host fisrt then WORKDIR
      - ./:/var/lib/app
    ports:
      - 8080:8080
  database:
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_USER: sergio
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: database
    container_name: api_container_db
    volumes:
      - database:/var/lib/mysql
volumes:
  database: {}
